## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Global
global:
  image:
    repository: quay.io/argoproj/argocd
    tag: v2.10.4
    imagePullPolicy: IfNotPresent
  securityContext: {}
  #  runAsUser: 999
  #  runAsGroup: 999
  #  fsGroup: 999
  imagePullSecrets: []
  hostAliases: []
  # - ip: 10.20.30.40
  #   hostnames:
  #   - git.myhostname
## Server
server:
  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true
  config:
    repositories: |
      - type: git
        url: git@gitlab.creativebox.dev:creativebox/gitops/argocd.git
        sshPrivateKeySecret:
          name: argocd-repo-ssh-key
          key: sshPrivateKey
      - type: git
        url: git@gitlab.creativebox.dev:creativebox/gitops/gitops-dev.git
        sshPrivateKeySecret:
          name: argocd-repo-ssh-key
          key: sshPrivateKey            
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
  additionalApplications: 
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ../values-override.yaml
        path: argocd-install/argo-cd
        repoURL: git@gitlab.creativebox.dev:creativebox/gitops/argocd.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true        
    - name: argocd-apps
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-apps
        repoURL: git@gitlab.creativebox.dev:creativebox/gitops/argocd.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: argocd-appprojects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-appprojects
        repoURL: git@gitlab.creativebox.dev:creativebox/gitops/argocd.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
  additionalProjects: 
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
  ## Server service configuration
  service:
    annotations: {}
    labels: {}
    type: NodePort
    ## For node port default ports
    nodePortHttp: 32080
    nodePortHttps: 32443
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https
    namedTargetPort: true
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalIPs: []
config:
  knownHosts:
    data:
      ssh_known_hosts: |
        gitlab.creativebox.dev ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCXLWeKSgZu7R+vGucAeYuGWhjY4ixOCn81m5nB2p6ZIt7BZczp0N4JcJtHCuFT0SNZ37+Izfo1lvRMJWh3xkHouXnNeYRbg8qNXYqpftn4MbOTjru6zxjsyG68njfwVXQnKOF+ZMMB8iUYoiIHjvZKu703fDXbNB60CbykoZnZ5TWfDhn1piCY12RMrVkJI6DJCv3zp+8oGJsEL6ltOcfPtRaOE43oMsPfk1VhNAUt42moTg7ydMusJXZoRcuj3bxXwGUAV4dDgbXkd5IlBhGrqHfAam7GhX6gYhl7fxDqy9X46MW8hywk4Jzzf7d1HSBucoGURt41cNYOhkr/J29qaeomivsOXaI+tXBSip3rJxs0qlR3FPSjCEEQNeXlEZLzwGNyvBjgMMyTtfLvi7r1Ytf6Gifkyw2atoBIVcYZlQileRQ7nh5U77h0CfHWGylpOQPP9Vl4EESdTDTn9HFInPbXFJl9vkodeboqaMlFIghbXCnk1eoYsT+pYlRCWSM=